set(_CATKIN_CURRENT_PACKAGE "multi_car_goal")
set(multi_car_goal_VERSION "0.0.0")
set(multi_car_goal_MAINTAINER "colin <shichunguo@gmail.com>")
set(multi_car_goal_PACKAGE_FORMAT "2")
set(multi_car_goal_BUILD_DEPENDS "roscpp" "tf2" "tf2_ros")
set(multi_car_goal_BUILD_EXPORT_DEPENDS "roscpp" "tf2" "tf2_ros")
set(multi_car_goal_BUILDTOOL_DEPENDS "catkin")
set(multi_car_goal_BUILDTOOL_EXPORT_DEPENDS )
set(multi_car_goal_EXEC_DEPENDS "roscpp" "tf2" "tf2_ros")
set(multi_car_goal_RUN_DEPENDS "roscpp" "tf2" "tf2_ros")
set(multi_car_goal_TEST_DEPENDS )
set(multi_car_goal_DOC_DEPENDS )
set(multi_car_goal_URL_WEBSITE "http://autolabor.com.cn")
set(multi_car_goal_URL_BUGTRACKER "")
set(multi_car_goal_URL_REPOSITORY "")
set(multi_car_goal_DEPRECATED "")