set(_CATKIN_CURRENT_PACKAGE "rviz_navigation_tools")
set(rviz_navigation_tools_VERSION "0.0.0")
set(rviz_navigation_tools_MAINTAINER "colin <shichunguo@gmail.com>")
set(rviz_navigation_tools_PACKAGE_FORMAT "1")
set(rviz_navigation_tools_BUILD_DEPENDS "roscpp" "rviz" "tf2" "tf2_ros" "qtbase5-dev")
set(rviz_navigation_tools_BUILD_EXPORT_DEPENDS "libqt5-core" "tf2" "tf2_ros" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_navigation_tools_BUILDTOOL_DEPENDS "catkin")
set(rviz_navigation_tools_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_navigation_tools_EXEC_DEPENDS "libqt5-core" "tf2" "tf2_ros" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_navigation_tools_RUN_DEPENDS "libqt5-core" "tf2" "tf2_ros" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_navigation_tools_TEST_DEPENDS )
set(rviz_navigation_tools_DOC_DEPENDS )
set(rviz_navigation_tools_URL_WEBSITE "http://autolabor.com.cn")
set(rviz_navigation_tools_URL_BUGTRACKER "")
set(rviz_navigation_tools_URL_REPOSITORY "")
set(rviz_navigation_tools_DEPRECATED "")