set(_CATKIN_CURRENT_PACKAGE "rviz_keyboard_twist")
set(rviz_keyboard_twist_VERSION "0.0.0")
set(rviz_keyboard_twist_MAINTAINER "colin <shichunguo@gmail.com>")
set(rviz_keyboard_twist_PACKAGE_FORMAT "1")
set(rviz_keyboard_twist_BUILD_DEPENDS "roscpp" "rviz" "qtbase5-dev")
set(rviz_keyboard_twist_BUILD_EXPORT_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_keyboard_twist_BUILDTOOL_DEPENDS "catkin")
set(rviz_keyboard_twist_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_keyboard_twist_EXEC_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_keyboard_twist_RUN_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_keyboard_twist_TEST_DEPENDS )
set(rviz_keyboard_twist_DOC_DEPENDS )
set(rviz_keyboard_twist_URL_WEBSITE "http://autolabor.com.cn")
set(rviz_keyboard_twist_URL_BUGTRACKER "")
set(rviz_keyboard_twist_URL_REPOSITORY "")
set(rviz_keyboard_twist_DEPRECATED "")