// Generated by gencpp from file autolabor_simulation_stage/ObstacleMap.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAP_H
#define AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAP_H

#include <ros/service_traits.h>


#include <autolabor_simulation_stage/ObstacleMapRequest.h>
#include <autolabor_simulation_stage/ObstacleMapResponse.h>


namespace autolabor_simulation_stage
{

struct ObstacleMap
{

typedef ObstacleMapRequest Request;
typedef ObstacleMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObstacleMap
} // namespace autolabor_simulation_stage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleMap > {
  static const char* value()
  {
    return "cb18b08a081674fbfa15ea3f0864a898";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMap&) { return value(); }
};

template<>
struct DataType< ::autolabor_simulation_stage::ObstacleMap > {
  static const char* value()
  {
    return "autolabor_simulation_stage/ObstacleMap";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMap&) { return value(); }
};


// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleMapRequest> should match
// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleMap >
template<>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_simulation_stage::ObstacleMap >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_simulation_stage::ObstacleMapRequest> should match
// service_traits::DataType< ::autolabor_simulation_stage::ObstacleMap >
template<>
struct DataType< ::autolabor_simulation_stage::ObstacleMapRequest>
{
  static const char* value()
  {
    return DataType< ::autolabor_simulation_stage::ObstacleMap >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleMapResponse> should match
// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleMap >
template<>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_simulation_stage::ObstacleMap >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_simulation_stage::ObstacleMapResponse> should match
// service_traits::DataType< ::autolabor_simulation_stage::ObstacleMap >
template<>
struct DataType< ::autolabor_simulation_stage::ObstacleMapResponse>
{
  static const char* value()
  {
    return DataType< ::autolabor_simulation_stage::ObstacleMap >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAP_H
