// Generated by gencpp from file autolabor_simulation_stage/ObstacleMapRequest.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPREQUEST_H
#define AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autolabor_simulation_stage
{
template <class ContainerAllocator>
struct ObstacleMapRequest_
{
  typedef ObstacleMapRequest_<ContainerAllocator> Type;

  ObstacleMapRequest_()
    : ignore_obstacle_id()  {
    }
  ObstacleMapRequest_(const ContainerAllocator& _alloc)
    : ignore_obstacle_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _ignore_obstacle_id_type;
  _ignore_obstacle_id_type ignore_obstacle_id;





  typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleMapRequest_

typedef ::autolabor_simulation_stage::ObstacleMapRequest_<std::allocator<void> > ObstacleMapRequest;

typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapRequest > ObstacleMapRequestPtr;
typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapRequest const> ObstacleMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator1> & lhs, const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ignore_obstacle_id == rhs.ignore_obstacle_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator1> & lhs, const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autolabor_simulation_stage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56f5b1346c17daa6f8802683495a7007";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56f5b1346c17daa6ULL;
  static const uint64_t static_value2 = 0xf8802683495a7007ULL;
};

template<class ContainerAllocator>
struct DataType< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autolabor_simulation_stage/ObstacleMapRequest";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] ignore_obstacle_id\n"
;
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ignore_obstacle_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autolabor_simulation_stage::ObstacleMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "ignore_obstacle_id[]" << std::endl;
    for (size_t i = 0; i < v.ignore_obstacle_id.size(); ++i)
    {
      s << indent << "  ignore_obstacle_id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ignore_obstacle_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPREQUEST_H
