// Generated by gencpp from file autolabor_simulation_stage/ObstacleMapResponse.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPRESPONSE_H
#define AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>

namespace autolabor_simulation_stage
{
template <class ContainerAllocator>
struct ObstacleMapResponse_
{
  typedef ObstacleMapResponse_<ContainerAllocator> Type;

  ObstacleMapResponse_()
    : obstacle_map()  {
    }
  ObstacleMapResponse_(const ContainerAllocator& _alloc)
    : obstacle_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _obstacle_map_type;
  _obstacle_map_type obstacle_map;





  typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleMapResponse_

typedef ::autolabor_simulation_stage::ObstacleMapResponse_<std::allocator<void> > ObstacleMapResponse;

typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapResponse > ObstacleMapResponsePtr;
typedef boost::shared_ptr< ::autolabor_simulation_stage::ObstacleMapResponse const> ObstacleMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator1> & lhs, const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle_map == rhs.obstacle_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator1> & lhs, const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autolabor_simulation_stage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f82372032c968bba9627480de409827a";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf82372032c968bbaULL;
  static const uint64_t static_value2 = 0x9627480de409827aULL;
};

template<class ContainerAllocator>
struct DataType< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autolabor_simulation_stage/ObstacleMapResponse";
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/OccupancyGrid obstacle_map\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autolabor_simulation_stage::ObstacleMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "obstacle_map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacle_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLEMAPRESPONSE_H
