set(_CATKIN_CURRENT_PACKAGE "cartographer_initialpose")
set(cartographer_initialpose_VERSION "0.0.0")
set(cartographer_initialpose_MAINTAINER "Colin <shichunguo@gmail.com>")
set(cartographer_initialpose_PACKAGE_FORMAT "2")
set(cartographer_initialpose_BUILD_DEPENDS "cartographer_ros_msgs" "roscpp" "tf")
set(cartographer_initialpose_BUILD_EXPORT_DEPENDS "cartographer_ros_msgs" "roscpp" "tf")
set(cartographer_initialpose_BUILDTOOL_DEPENDS "catkin")
set(cartographer_initialpose_BUILDTOOL_EXPORT_DEPENDS )
set(cartographer_initialpose_EXEC_DEPENDS "cartographer_ros" "roscpp" "tf")
set(cartographer_initialpose_RUN_DEPENDS "cartographer_ros" "roscpp" "tf" "cartographer_ros_msgs")
set(cartographer_initialpose_TEST_DEPENDS )
set(cartographer_initialpose_DOC_DEPENDS )
set(cartographer_initialpose_URL_WEBSITE "http://autolabor.com.cn")
set(cartographer_initialpose_URL_BUGTRACKER "")
set(cartographer_initialpose_URL_REPOSITORY "")
set(cartographer_initialpose_DEPRECATED "")