set(_CATKIN_CURRENT_PACKAGE "rslidar_sdk")
set(rslidar_sdk_VERSION "1.5.0")
set(rslidar_sdk_MAINTAINER "robosense <ron.zheng@robosense.cn>")
set(rslidar_sdk_PACKAGE_FORMAT "1")
set(rslidar_sdk_BUILD_DEPENDS "roscpp" "sensor_msgs" "roslib")
set(rslidar_sdk_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "roslib")
set(rslidar_sdk_BUILDTOOL_DEPENDS "catkin")
set(rslidar_sdk_BUILDTOOL_EXPORT_DEPENDS )
set(rslidar_sdk_EXEC_DEPENDS "roscpp" "sensor_msgs" "roslib")
set(rslidar_sdk_RUN_DEPENDS "roscpp" "sensor_msgs" "roslib")
set(rslidar_sdk_TEST_DEPENDS )
set(rslidar_sdk_DOC_DEPENDS )
set(rslidar_sdk_URL_WEBSITE "")
set(rslidar_sdk_URL_BUGTRACKER "")
set(rslidar_sdk_URL_REPOSITORY "")
set(rslidar_sdk_DEPRECATED "")