#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/xyz/autolabor/devel_isolated/cartographer_ros_msgs:/home/xyz/autolabor/devel_isolated/camera_calibration:/home/xyz/autolabor/devel_isolated/autolabor_test_launch:/home/xyz/autolabor/devel_isolated/autolabor_simulation_object:/home/xyz/autolabor/devel_isolated/autolabor_simulation_lidar:/home/xyz/autolabor/devel_isolated/autolabor_simulation_stage:/home/xyz/autolabor/devel_isolated/autolabor_simulation_location:/home/xyz/autolabor/devel_isolated/autolabor_simulation_base:/home/xyz/autolabor/devel_isolated/autolabor_pro1_driver:/home/xyz/autolabor/devel_isolated/autolabor_navigation_launch:/home/xyz/autolabor/devel_isolated/autolabor_keyboard_control:/home/xyz/autolabor/devel_isolated/autolabor_description:/home/xyz/autolabor/devel_isolated/autolabor_canbus_driver:/opt/ros/noetic:/home/xyz/autolabor/devel_isolated/cartographer:/home/xyz/autolabor/devel_isolated/cartographer'
export LD_LIBRARY_PATH='/home/xyz/autolabor/devel_isolated/camera_calibration/lib:/home/xyz/autolabor/devel_isolated/autolabor_test_launch/lib:/home/xyz/autolabor/devel_isolated/autolabor_simulation_object/lib:/home/xyz/autolabor/devel_isolated/autolabor_simulation_lidar/lib:/home/xyz/autolabor/devel_isolated/autolabor_simulation_stage/lib:/home/xyz/autolabor/devel_isolated/autolabor_simulation_location/lib:/home/xyz/autolabor/devel_isolated/autolabor_simulation_base/lib:/home/xyz/autolabor/devel_isolated/autolabor_pro1_driver/lib:/home/xyz/autolabor/devel_isolated/autolabor_navigation_launch/lib:/home/xyz/autolabor/devel_isolated/autolabor_keyboard_control/lib:/home/xyz/autolabor/devel_isolated/autolabor_description/lib:/home/xyz/autolabor/devel_isolated/autolabor_canbus_driver/lib:/opt/ros/noetic/lib:/home/xyz/autolabor/devel_isolated/cartographer/lib:/home/xyz/autolabor/devel_isolated/cartographer/lib/x86_64-linux-gnu:/home/xyz/autolabor/devel_isolated/cartographer/lib:/usr/local/cuda-11.6/lib64:/opt/TensorRT-8.4.3.1/lib:/usr/local/cuda-11.6/lib64'
export PATH='/opt/ros/noetic/bin:/home/xyz/autolabor/devel_isolated/cartographer/bin:/home/xyz/autolabor/devel_isolated/cartographer/bin:/home/xyz/miniconda3/condabin:/opt/TensorRT-8.4.3.1/bin:/usr/local/cuda-11.6/bin:/home/xyz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/xyz/autolabor/devel_isolated/camera_calibration/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_test_launch/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_simulation_object/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_simulation_lidar/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_simulation_stage/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_simulation_location/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_simulation_base/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_pro1_driver/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_navigation_launch/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_keyboard_control/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_description/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/autolabor_canbus_driver/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/cartographer/lib/pkgconfig:/home/xyz/autolabor/devel_isolated/cartographer/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig'
export PYTHONPATH='/home/xyz/autolabor/devel_isolated/camera_calibration/lib/python3/dist-packages:/home/xyz/autolabor/devel_isolated/autolabor_simulation_stage/lib/python3/dist-packages:/home/xyz/autolabor/devel_isolated/autolabor_pro1_driver/lib/python3/dist-packages:/home/xyz/autolabor/devel_isolated/autolabor_canbus_driver/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/xyz/autolabor/devel_isolated/cartographer/lib/python3/dist-packages:/home/xyz/carla_0.9.13/PythonAPI:/home/xyz/carla_0.9.13/PythonAPI/util:/home/xyz/carla_0.9.13/PythonAPI/carla:/home/xyz/carla_0.9.13/PythonAPI/carla/agent:/home/xyz/carla_0.9.13/PythonAPI/carla/dist/carla-0.9.13-py3.7-linux-x86_64.egg'
export ROSLISP_PACKAGE_DIRECTORIES="/home/xyz/autolabor/devel_isolated/cartographer_ros_msgs/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/xyz/autolabor/src/mapping/cartographer_ros/cartographer_ros_msgs:$ROS_PACKAGE_PATH"