# CMake generated Testfile for 
# Source directory: /home/xyz/autolabor/src/driver/lidar/urg_node
# Build directory: /home/xyz/autolabor/build_isolated/urg_node
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_urg_node_roslint_package "/home/xyz/autolabor/build_isolated/urg_node/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/xyz/autolabor/build_isolated/urg_node/test_results/urg_node/roslint-urg_node.xml" "--working-dir" "/home/xyz/autolabor/build_isolated/urg_node" "--return-code" "/opt/ros/noetic/share/roslint/cmake/../../../lib/roslint/test_wrapper /home/xyz/autolabor/build_isolated/urg_node/test_results/urg_node/roslint-urg_node.xml make roslint_urg_node")
set_tests_properties(_ctest_urg_node_roslint_package PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslint/cmake/roslint-extras.cmake;67;catkin_run_tests_target;/home/xyz/autolabor/src/driver/lidar/urg_node/CMakeLists.txt;82;roslint_add_test;/home/xyz/autolabor/src/driver/lidar/urg_node/CMakeLists.txt;0;")
add_test(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch "/home/xyz/autolabor/build_isolated/urg_node/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/xyz/autolabor/build_isolated/urg_node/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/xyz/autolabor/build_isolated/urg_node/test_results/urg_node" "/opt/ros/noetic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/xyz/autolabor/build_isolated/urg_node/test_results/urg_node/roslaunch-check_launch_urg_lidar.launch.xml\" \"/home/xyz/autolabor/src/driver/lidar/urg_node/launch/urg_lidar.launch\" ")
set_tests_properties(_ctest_urg_node_roslaunch-check_launch_urg_lidar.launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/roslaunch/cmake/roslaunch-extras.cmake;66;catkin_run_tests_target;/home/xyz/autolabor/src/driver/lidar/urg_node/CMakeLists.txt;85;roslaunch_add_file_check;/home/xyz/autolabor/src/driver/lidar/urg_node/CMakeLists.txt;0;")
subdirs("gtest")
