set(_CATKIN_CURRENT_PACKAGE "rviz_autolabor_calibration")
set(rviz_autolabor_calibration_VERSION "0.0.0")
set(rviz_autolabor_calibration_MAINTAINER "Colin <shichunguo@gmail.com>")
set(rviz_autolabor_calibration_PACKAGE_FORMAT "1")
set(rviz_autolabor_calibration_BUILD_DEPENDS "roscpp" "rviz" "qtbase5-dev")
set(rviz_autolabor_calibration_BUILD_EXPORT_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_autolabor_calibration_BUILDTOOL_DEPENDS "catkin")
set(rviz_autolabor_calibration_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_autolabor_calibration_EXEC_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_autolabor_calibration_RUN_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz")
set(rviz_autolabor_calibration_TEST_DEPENDS )
set(rviz_autolabor_calibration_DOC_DEPENDS )
set(rviz_autolabor_calibration_URL_WEBSITE "http://autolabor.com.cn")
set(rviz_autolabor_calibration_URL_BUGTRACKER "")
set(rviz_autolabor_calibration_URL_REPOSITORY "")
set(rviz_autolabor_calibration_DEPRECATED "")