set(_CATKIN_CURRENT_PACKAGE "pico_zense_driver")
set(pico_zense_driver_VERSION "0.0.0")
set(pico_zense_driver_MAINTAINER "colin <shichunguo@gmail.com>")
set(pico_zense_driver_PACKAGE_FORMAT "2")
set(pico_zense_driver_BUILD_DEPENDS "roscpp" "tf2_ros" "tf" "sensor_msgs")
set(pico_zense_driver_BUILD_EXPORT_DEPENDS "roscpp" "tf2_ros" "tf" "sensor_msgs")
set(pico_zense_driver_BUILDTOOL_DEPENDS "catkin")
set(pico_zense_driver_BUILDTOOL_EXPORT_DEPENDS )
set(pico_zense_driver_EXEC_DEPENDS "roscpp" "tf2_ros" "tf" "sensor_msgs")
set(pico_zense_driver_RUN_DEPENDS "roscpp" "tf2_ros" "tf" "sensor_msgs")
set(pico_zense_driver_TEST_DEPENDS )
set(pico_zense_driver_DOC_DEPENDS )
set(pico_zense_driver_URL_WEBSITE "")
set(pico_zense_driver_URL_BUGTRACKER "")
set(pico_zense_driver_URL_REPOSITORY "")
set(pico_zense_driver_DEPRECATED "")